http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager-core
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Adityakumar Singh
user.email=adityakumar_singh@epam.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github.com:XenoCod/Code_to_Glory.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin1.url=git@github.com:XenoCod/Code-Commit.git
remote.origin1.fetch=+refs/heads/*:refs/remotes/origin1/*
branch.master.remote=origin1
branch.master.merge=refs/heads/master
remote.origin2.url=git@github.com:XenoCod/Code-Commit.git
remote.origin2.fetch=+refs/heads/*:refs/remotes/origin2/*
branch.arrays.remote=origin1
branch.arrays.merge=refs/heads/arrays
gui.wmstate=normal
gui.geometry=1109x563+96+96 216 255
